window.referenceData = {
  productTruth: {
    product: "MUMUKI Honey Banana BDRN Ampoule",
    oneLiner: "Banana natural t0x went viral. MUMUKI made the clean ampoule version.",
    core: "Banana + honey stops people. Ampoule makes it usable.",
    guardrail: "Do not use Botox directly. Use t0x if needed, and keep it as a TikTok trend angle, not a medical promise."
  },
  skit: [
    {
      id: "skit-claudia-glow-01",
      title: "Messy Beauty Hack",
      source: "Claudia Glow reference",
      creator: "@claudia_glow01",
      videoId: "7626188830231629086",
      url: "https://www.tiktok.com/@claudia_glow01/video/7626188830231629086",
      localVideo: "assets/videos/skit-claudia_glow01-7626188830231629086.mp4",
      status: "Needs teardown",
      pattern: "A creator does something visually weird or messy for beauty, then introduces a cleaner version.",
      whyItWorks: "The visual is instantly understandable. It makes viewers ask why someone is putting food on their face.",
      mumukiTranslation: "Banana and honey on the face stops people, but MUMUKI is the version they can actually use every day.",
      openingShot: "Hold banana and honey near the bathroom mirror like you are about to put breakfast on your face.",
      overlay: "I wanted glass skin... but not like this",
      shotList: [
        "Show banana and honey in the bathroom",
        "Pause like you know this is ridiculous",
        "Reveal MUMUKI ampoule",
        "Apply ampoule close to camera",
        "End on glass-skin payoff"
      ],
      rawDemo: "Add Yicheng raw demo here"
    },
    {
      id: "skit-lance-shopfinds-01",
      title: "Product Solves the Annoying Part",
      source: "Lance Shop Finds reference",
      creator: "@lanceshopfinds1",
      videoId: "7618446657650314509",
      url: "https://www.tiktok.com/@lanceshopfinds1/video/7618446657650314509",
      localVideo: "assets/videos/skit-lanceshopfinds1-7618446657650314509.mp4",
      status: "Needs teardown",
      pattern: "Show the annoying version first. Then reveal the product as the shortcut.",
      whyItWorks: "It does not start with a product pitch. It starts with the annoying behavior the product replaces.",
      mumukiTranslation: "DIY banana-honey skincare is sticky. The ampoule gives the same glass-skin idea without the mess.",
      openingShot: "Show a spoon, honey, banana, and a confused face. Cut to the ampoule.",
      overlay: "Nobody is doing this every day",
      shotList: [
        "Show the messy DIY setup",
        "Call out why nobody wants to do this daily",
        "Cut to the ampoule",
        "Show one clean application shot",
        "Say this is the daily version"
      ],
      rawDemo: "Add Yicheng raw demo here"
    }
  ],
  viralNonTikTokShop: [
    {
      id: "viral-non-tts-natural-nadine-banana-peel",
      title: "Banana Peel Skincare Scrub",
      source: "Viral non-TikTokShop video",
      creator: "@thenaturalnadine",
      videoId: "7318924509522791710",
      url: "https://www.tiktok.com/@thenaturalnadine/video/7318924509522791710",
      localVideo: "assets/videos/viral-natural-nadine-banana-peel.mp4",
      status: "Outside TTS",
      pattern: "Banana peel skincare is framed as a natural skin hack for hydration, tightening, and healthier-looking skin.",
      whyItWorks: "It proves the banana skincare idea already exists as non-commerce content. The viewer does not need to be taught why banana on skin is interesting.",
      mumukiTranslation: "MUMUKI can take the same banana-skin curiosity and turn it into a cleaner ampoule story."
    },
    {
      id: "viral-non-tts-duoheadspa-banana-facial",
      title: "Banana Fruit Facial",
      source: "Viral non-TikTokShop video",
      creator: "@duoheadspa",
      videoId: "7427159569874390315",
      url: "https://www.tiktok.com/@duoheadspa/video/7427159569874390315",
      localVideo: "assets/videos/viral-duoheadspa-7427159569874390315.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-kevinnkylee-banana-tightening",
      title: "Banana Skin Tightening Hack",
      source: "Viral non-TikTokShop video",
      creator: "@kevinnkylee",
      videoId: "7459763407668006152",
      url: "https://www.tiktok.com/@kevinnkylee/video/7459763407668006152",
      localVideo: "assets/videos/viral-kevinnkylee-7459763407668006152.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-sheenaanayaaa-banana-peel-test",
      title: "Banana Peel Tightening Test",
      source: "Viral non-TikTokShop video",
      creator: "@sheenaanayaaa",
      videoId: "7331862916603612462",
      url: "https://www.tiktok.com/@sheenaanayaaa/video/7331862916603612462",
      localVideo: "assets/videos/viral-sheenaanayaaa-7331862916603612462.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-shamiebirungi19-honey-glow",
      title: "Honey Skin Glow Hack",
      source: "Viral non-TikTokShop video",
      creator: "@shamiebirungi19",
      videoId: "7593798567966297355",
      url: "https://www.tiktok.com/@shamiebirungi19/video/7593798567966297355",
      localVideo: "assets/videos/viral-shamiebirungi19-7593798567966297355.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop honey skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-jaimesskin-manuka-honey",
      title: "Manuka Honey Face Mask",
      source: "Viral non-TikTokShop video",
      creator: "@jaimesskin",
      videoId: "7545915943940050231",
      url: "https://www.tiktok.com/@jaimesskin/video/7545915943940050231",
      localVideo: "assets/videos/viral-jaimesskin-7545915943940050231.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop honey skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-katiejanehughes-banana-skin-facial",
      title: "Banana Skin Facial",
      source: "Viral non-TikTokShop video",
      creator: "@katiejanehughes",
      videoId: "7355150760293747998",
      url: "https://www.tiktok.com/@katiejanehughes/video/7355150760293747998",
      localVideo: "assets/videos/viral-katiejanehughes-7355150760293747998.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-victoria-benitez-banana-skin",
      title: "Banana for Skin Girlies",
      source: "Viral non-TikTokShop video",
      creator: "@victoria__benitez",
      videoId: "7330117596110392619",
      url: "https://www.tiktok.com/@victoria__benitez/video/7330117596110392619",
      localVideo: "assets/videos/viral-victoria__benitez-7330117596110392619.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-iamedsonbrandao-frozen-banana",
      title: "Frozen Banana Lift Hack",
      source: "Viral non-TikTokShop video",
      creator: "@iamedsonbrandao",
      videoId: "7621189679148272928",
      url: "https://www.tiktok.com/@iamedsonbrandao/video/7621189679148272928",
      localVideo: "assets/videos/viral-iamedsonbrandao-7621189679148272928.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop frozen banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-byzareefa-banana-peel-mask",
      title: "Banana Peel DIY Mask",
      source: "Viral non-TikTokShop video",
      creator: "@byzareefa",
      videoId: "7447707169664879915",
      url: "https://www.tiktok.com/@byzareefa/video/7447707169664879915",
      localVideo: "assets/videos/viral-byzareefa-7447707169664879915.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-thejenjones-banana-peel-t0x",
      title: "Banana Peel Natural t0x",
      source: "Viral non-TikTokShop video",
      creator: "@thejenjones",
      videoId: "7561970033195257101",
      url: "https://www.tiktok.com/@thejenjones/video/7561970033195257101",
      localVideo: "assets/videos/viral-thejenjones-7561970033195257101.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-zack-chug-banana-vs-t0x",
      title: "Banana vs t0x Hook",
      source: "Viral non-TikTokShop video",
      creator: "@zack.chug",
      videoId: "7627186004625018134",
      url: "https://www.tiktok.com/@zack.chug/video/7627186004625018134",
      localVideo: "assets/videos/viral-zack.chug-7627186004625018134.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-drewcanole-honey-facemask",
      title: "DIY Honey Face Mask",
      source: "Viral non-TikTokShop video",
      creator: "@drewcanole",
      videoId: "7579824086315011359",
      url: "https://www.tiktok.com/@drewcanole/video/7579824086315011359",
      localVideo: "assets/videos/viral-drewcanole-7579824086315011359.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop honey skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-kriziaraso-honey-facial",
      title: "Honey Facial Glow",
      source: "Viral non-TikTokShop video",
      creator: "@kriziaraso",
      videoId: "7555933284388146454",
      url: "https://www.tiktok.com/@kriziaraso/video/7555933284388146454",
      localVideo: "assets/videos/viral-kriziaraso-7555933284388146454.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop honey skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-bithhnh387-frozen-banana",
      title: "Frozen Banana Skincare",
      source: "Viral non-TikTokShop video",
      creator: "@bithhnh387",
      videoId: "7603074530570980638",
      url: "https://www.tiktok.com/@bithhnh387/video/7603074530570980638",
      localVideo: "assets/videos/viral-bithhnh387-7603074530570980638.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop banana skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-scottyscheller-honey",
      title: "Honey Health Hook",
      source: "Viral non-TikTokShop video",
      creator: "@scottyscheller",
      videoId: "7618385031932808462",
      url: "https://www.tiktok.com/@scottyscheller/video/7618385031932808462",
      localVideo: "assets/videos/viral-scottyscheller-7618385031932808462.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop honey reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-tenishaward1-honey-comb-facial",
      title: "Honey Comb Facial",
      source: "Viral non-TikTokShop video",
      creator: "@tenishaward1",
      videoId: "7446093862952815918",
      url: "https://www.tiktok.com/@tenishaward1/video/7446093862952815918",
      localVideo: "assets/videos/viral-tenishaward1-7446093862952815918.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop honey skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "viral-non-tts-tenishaward1-brighter-clearer-skin",
      title: "Brighter Clearer Skin",
      source: "Viral non-TikTokShop video",
      creator: "@tenishaward1",
      videoId: "7615701080982211853",
      url: "https://www.tiktok.com/@tenishaward1/video/7615701080982211853",
      localVideo: "assets/videos/viral-tenishaward1-7615701080982211853.mp4",
      status: "Outside TTS",
      pattern: "Outside TikTokShop honey skin reference.",
      whyItWorks: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    }
  ],
  talkingHead: [
    {
      id: "talking-head-iamsk8bordb-pdrn",
      title: "PDRN Just Works",
      source: "Talking head reference",
      creator: "@iamsk8bordb",
      videoId: "7618462796405148941",
      url: "https://www.tiktok.com/@iamsk8bordb/video/7618462796405148941",
      localVideo: "assets/videos/talking-iamsk8bordb-7618462796405148941.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-biohacking-babe-fine-lines",
      title: "Fine Lines Serum Talk",
      source: "Talking head reference",
      creator: "@biohacking.babe",
      videoId: "7628791249079700767",
      url: "https://www.tiktok.com/@biohacking.babe/video/7628791249079700767",
      localVideo: "assets/videos/talking-biohacking.babe-7628791249079700767.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-kajsa-ziebell-lines",
      title: "Under-Eye And Smile Line Hook",
      source: "Talking head reference",
      creator: "@kajsa.ziebell",
      videoId: "7618313975263956237",
      url: "https://www.tiktok.com/@kajsa.ziebell/video/7618313975263956237",
      localVideo: "assets/videos/talking-kajsa.ziebell-7618313975263956237.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-southwellness-face-card",
      title: "New Face Card At 35",
      source: "Talking head reference",
      creator: "@southwellness",
      videoId: "7621029735853722894",
      url: "https://www.tiktok.com/@southwellness/video/7621029735853722894",
      localVideo: "assets/videos/talking-southwellness-7621029735853722894.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-wellnessbenefitsonly-wrinkles",
      title: "Wrinkle Skin Hook",
      source: "Talking head reference",
      creator: "@wellnessbenefitsonly",
      videoId: "7624739135223336205",
      url: "https://www.tiktok.com/@wellnessbenefitsonly/video/7624739135223336205",
      localVideo: "assets/videos/talking-wellnessbenefitsonly-7624739135223336205.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-kaylavashti-turning-39",
      title: "Turning 39 Skin Hook",
      source: "Talking head reference",
      creator: "@kaylavashti",
      videoId: "7629543244132551949",
      url: "https://www.tiktok.com/@kaylavashti/video/7629543244132551949",
      localVideo: "assets/videos/talking-kaylavashti-7629543244132551949.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-joshadk-fine-lines",
      title: "Fine Lines Bundle Talk",
      source: "Talking head reference",
      creator: "@joshadk",
      videoId: "7626737286692130051",
      url: "https://www.tiktok.com/@joshadk/video/7626737286692130051",
      localVideo: "assets/videos/talking-joshadk-7626737286692130051.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-holisticglowupp-pdrn-bundle",
      title: "PDRN Bundle Explainer",
      source: "Talking head reference",
      creator: "@holisticglowupp",
      videoId: "7620648304128314655",
      url: "https://www.tiktok.com/@holisticglowupp/video/7620648304128314655",
      localVideo: "assets/videos/talking-holisticglowupp-7620648304128314655.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-elder-jack-7619128458060336415",
      title: "Elder Jack Skin Talk",
      source: "Talking head reference",
      creator: "@elder.jack",
      videoId: "7619128458060336415",
      url: "https://www.tiktok.com/@elder.jack/video/7619128458060336415",
      localVideo: "assets/videos/talking-elder.jack-7619128458060336415.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-elder-jack-pdrn-kbeauty",
      title: "PDRN K-Beauty Trend",
      source: "Talking head reference",
      creator: "@elder.jack",
      videoId: "7560208949903920414",
      url: "https://www.tiktok.com/@elder.jack/video/7560208949903920414",
      localVideo: "assets/videos/talking-elder.jack-7560208949903920414.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    },
    {
      id: "talking-head-little-miss-c-medicube-serum",
      title: "Medicube Powerhouse Serum",
      source: "Talking head reference",
      creator: "@little_miss_c_",
      videoId: "7628304350091300127",
      url: "https://www.tiktok.com/@little_miss_c_/video/7628304350091300127",
      localVideo: "assets/videos/talking-little_miss_c_-7628304350091300127.mp4",
      status: "Talking Head",
      pattern: "To be added after teardown.",
      mumukiTranslation: "To be added after teardown."
    }
  ],
  skitSlots: [
    "Messy DIY Hack",
    "Bathroom Looks Like Breakfast",
    "Friend Thinks You Are Making a Smoothie",
    "I Tried the TikTok Hack",
    "Lazy Girl Glass Skin",
    "K-beauty Made It Easier",
    "Expectation vs Reality",
    "Sticky Trend, Clean Ampoule",
    "One Product Replaces the Mess",
    "Banana Botox, But Daily"
  ]
};
