window.visualHookGroupsData = [
  {
    "id": "banana-peel-rub",
    "title": "Banana Peel Rub",
    "label": "Direct face rub",
    "why": "The easiest pattern to translate into MUMUKI ampoule application: same food-ingredient idea, but shifted from banana peel on skin to ampoule on skin.",
    "items": [
      {
        "id": "7355150760293747998-016",
        "videoId": "7355150760293747998",
        "creator": "@katiejanehughes",
        "title": "Banana Skin Facial",
        "clipPath": "content/visual-hook-mining/clips/katiejanehughes__banana-skin-facial__7355150760293747998_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 4.0,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "The creator is rubbing the inside of a banana peel directly onto her cheek.",
        "whyThisMomentMatters": "The unconventional use of a common food item as skincare creates immediate curiosity and stop-power.",
        "mumukiReuseNote": "Use this as a hook for the MUMUKI Honey Banana BDRN Ampoule by showing the product being applied in a similar motion to emphasize the 'natural' ingredient benefit."
      },
      {
        "id": "7330117596110392619-006",
        "videoId": "7330117596110392619",
        "creator": "@victoria__benitez",
        "title": "Banana for Skin Girlies",
        "clipPath": "content/visual-hook-mining/clips/victoria-benitez__banana-for-skin-girlies__7330117596110392619_v3_31flashlite/beat-01.mp4",
        "startSeconds": 6.5,
        "endSeconds": 10.0,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "The creator is holding a banana peel and directly rubbing the inner side of it against her cheek.",
        "whyThisMomentMatters": "This is the most shocking and attention-grabbing action in the video, creating immediate curiosity about the efficacy of banana peels on skin.",
        "mumukiReuseNote": "Use this as a 'don't do this' hook, transitioning to the professional, clean application of the MUMUKI Honey Banana BDRN Ampoule."
      },
      {
        "id": "7627186004625018134-084",
        "videoId": "7627186004625018134",
        "creator": "@zack.chug",
        "title": "Banana vs t0x Hook",
        "clipPath": "content/visual-hook-mining/clips/zack-chug__banana-vs-t0x-hook__7627186004625018134_v3_31flashlite/beat-01.mp4",
        "startSeconds": 6.5,
        "endSeconds": 9.0,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "The creator is aggressively rubbing a banana peel directly onto his face, with mashed banana residue sticking to his skin.",
        "whyThisMomentMatters": "High visual shock value; immediately establishes the DIY skincare angle with a relatable, slightly messy action.",
        "mumukiReuseNote": "Use this as a 'don't do this, do this instead' transition to introduce the MUMUKI ampoule as a cleaner, more effective alternative."
      },
      {
        "id": "7561970033195257101-052",
        "videoId": "7561970033195257101",
        "creator": "@thejenjones",
        "title": "Banana Peel Natural t0x",
        "clipPath": "content/visual-hook-mining/clips/thejenjones__banana-peel-natural-t0x__7561970033195257101_v3_31flashlite/beat-02.mp4",
        "startSeconds": 12.5,
        "endSeconds": 16.0,
        "momentBucket": "application_moment",
        "roleTag": "visual-demonstration",
        "clipPriority": 2,
        "visualEvidence": "The creator rubs the inside of the banana peel directly onto her cheek and under-eye area.",
        "whyThisMomentMatters": "Shows the direct application of the ingredient to the skin, which is a highly engaging 'DIY' visual.",
        "mumukiReuseNote": "Replace the banana peel with the application of the MUMUKI Ampoule to show the product being applied to the same facial zones."
      },
      {
        "id": "7318924509522791710-002",
        "videoId": "7318924509522791710",
        "creator": "@thenaturalnadine",
        "title": "Banana Peel Skincare Scrub",
        "clipPath": "content/visual-hook-mining/clips/thenaturalnadine__banana-peel-skincare-scrub__7318924509522791710_v3_31flashlite/beat-02.mp4",
        "startSeconds": 39.5,
        "endSeconds": 43.0,
        "momentBucket": "application_moment",
        "roleTag": "product-like application",
        "clipPriority": 2,
        "visualEvidence": "Close-up shot of the creator rubbing the banana peel under her eye and across her cheekbone.",
        "whyThisMomentMatters": "Demonstrates the specific application technique and highlights the 'skincare' aspect of the DIY method.",
        "mumukiReuseNote": "Use this framing to show the ampoule being applied to the under-eye area, emphasizing the product's targeted benefits."
      },
      {
        "id": "7331862916603612462-012",
        "videoId": "7331862916603612462",
        "creator": "@sheenaanayaaa",
        "title": "Banana Peel Tightening Test",
        "clipPath": "content/visual-hook-mining/clips/sheenaanayaaa__banana-peel-tightening-test__7331862916603612462_v3_31flashlite/beat-02.mp4",
        "startSeconds": 5.0,
        "endSeconds": 8.0,
        "momentBucket": "application_moment",
        "roleTag": "visual-action",
        "clipPriority": 2,
        "visualEvidence": "The creator rubs the inside of a banana peel directly onto her cheek and jawline.",
        "whyThisMomentMatters": "Demonstrates the 'DIY' application method that viewers find intriguing.",
        "mumukiReuseNote": "Show the application of the MUMUKI ampoule in a similar sweeping motion to emphasize texture and coverage."
      },
      {
        "id": "7355150760293747998-017",
        "videoId": "7355150760293747998",
        "creator": "@katiejanehughes",
        "title": "Banana Skin Facial",
        "clipPath": "content/visual-hook-mining/clips/katiejanehughes__banana-skin-facial__7355150760293747998_v3_31flashlite/beat-02.mp4",
        "startSeconds": 17.0,
        "endSeconds": 20.0,
        "momentBucket": "application_demonstration",
        "roleTag": "product-like application",
        "clipPriority": 2,
        "visualEvidence": "Close-up of the creator rubbing the banana peel on one side of her face.",
        "whyThisMomentMatters": "The 'half-face' experiment is a classic, highly effective visual trope for demonstrating product efficacy.",
        "mumukiReuseNote": "Replicate the half-face application test with the MUMUKI ampoule to visually prove the glow/tightening effect."
      },
      {
        "id": "7459763407668006152-037",
        "videoId": "7459763407668006152",
        "creator": "@kevinnkylee",
        "title": "Banana Skin Tightening Hack",
        "clipPath": "content/visual-hook-mining/clips/kevinnkylee__banana-skin-tightening-hack__7459763407668006152_v3_31flashlite/beat-02.mp4",
        "startSeconds": 3.0,
        "endSeconds": 6.0,
        "momentBucket": "application_moment",
        "roleTag": "visual-demonstration",
        "clipPriority": 2,
        "visualEvidence": "The creator rubs the inside of a banana peel directly onto his cheek and forehead.",
        "whyThisMomentMatters": "Direct application of the ingredient to the skin is the core visual hook that validates the DIY skincare angle.",
        "mumukiReuseNote": "Show the texture of the Honey Banana ampoule being applied to the skin in a similar motion to emphasize the 'banana' benefit."
      }
    ]
  },
  {
    "id": "banana-face-mask",
    "title": "Banana Face Mask / Patches",
    "label": "Banana on face",
    "why": "Strong weird visual. Useful for a hook built around: you would not do this every day, so use this instead.",
    "items": [
      {
        "id": "7427159569874390315-021",
        "videoId": "7427159569874390315",
        "creator": "@duoheadspa",
        "title": "Banana Fruit Facial",
        "clipPath": "content/visual-hook-mining/clips/duoheadspa__banana-fruit-facial__7427159569874390315_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 2.0,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "A close-up of a person's face completely covered in thin, circular slices of banana.",
        "whyThisMomentMatters": "The bizarre and visually striking image of a face covered in banana slices creates immediate curiosity and 'stop-scrolling' effect.",
        "mumukiReuseNote": "Use as a visual hook to contrast the 'messy DIY' approach with the clean, professional application of the MUMUKI Honey Banana BDRN Ampoule."
      },
      {
        "id": "7331862916603612462-013",
        "videoId": "7331862916603612462",
        "creator": "@sheenaanayaaa",
        "title": "Banana Peel Tightening Test",
        "clipPath": "content/visual-hook-mining/clips/sheenaanayaaa__banana-peel-tightening-test__7331862916603612462_v3_31flashlite/beat-03.mp4",
        "startSeconds": 10.5,
        "endSeconds": 13.5,
        "momentBucket": "application_moment",
        "roleTag": "visual-action",
        "clipPriority": 3,
        "visualEvidence": "The creator places pieces of banana peel under her eyes like eye patches.",
        "whyThisMomentMatters": "Creates a 'skincare hack' visual that is highly shareable.",
        "mumukiReuseNote": "Show the ampoule being applied to the under-eye area to highlight its targeted benefits."
      },
      {
        "id": "7331862916603612462-014",
        "videoId": "7331862916603612462",
        "creator": "@sheenaanayaaa",
        "title": "Banana Peel Tightening Test",
        "clipPath": "content/visual-hook-mining/clips/sheenaanayaaa__banana-peel-tightening-test__7331862916603612462_v3_31flashlite/beat-04.mp4",
        "startSeconds": 16.0,
        "endSeconds": 19.0,
        "momentBucket": "process_moment",
        "roleTag": "visual-action",
        "clipPriority": 4,
        "visualEvidence": "The creator has multiple pieces of banana peel stuck to her face as a mask.",
        "whyThisMomentMatters": "Strong visual impact of a 'DIY mask' that stops the scroll.",
        "mumukiReuseNote": "Show the ampoule applied as a thick, nourishing layer to mimic the 'mask' effect."
      }
    ]
  },
  {
    "id": "honey-drip-texture",
    "title": "Honey Drip Texture",
    "label": "Honey drip / stretch",
    "why": "Honey has natural stop-power: slow, sticky, shiny, and stretchy. Useful as a texture pattern interrupt in the opening.",
    "items": [
      {
        "id": "7446093862952815918-026",
        "videoId": "7446093862952815918",
        "creator": "@tenishaward1",
        "title": "Honey Comb Facial",
        "clipPath": "content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 3.0,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "The creator is holding a large piece of raw honeycomb and squeezing it directly onto her forehead, with honey dripping down her face.",
        "whyThisMomentMatters": "The raw, messy, and tactile nature of squeezing honeycomb directly onto the face creates an immediate 'what is she doing?' curiosity gap.",
        "mumukiReuseNote": "Use this as a high-impact hook by showing the rich, viscous texture of the MUMUKI ampoule being applied in a similar close-up, satisfying way."
      },
      {
        "id": "7618385031932808462-074",
        "videoId": "7618385031932808462",
        "creator": "@scottyscheller",
        "title": "Honey Health Hook",
        "clipPath": "content/visual-hook-mining/clips/scottyscheller__honey-health-hook__7618385031932808462_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 2.5,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "Close-up of a spoon lifting a thick, viscous, golden honey from a jar, creating a long, slow drip.",
        "whyThisMomentMatters": "The extreme close-up and the satisfying, thick texture of the honey immediately grab attention.",
        "mumukiReuseNote": "Use a similar close-up shot of the honey-infused ampoule texture to demonstrate its richness and quality."
      },
      {
        "id": "7593798567966297355-061",
        "videoId": "7593798567966297355",
        "creator": "@shamiebirungi19",
        "title": "Honey Skin Glow Hack",
        "clipPath": "content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 3.5,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "Honey is being poured directly from a bottle onto the center of the creator's forehead.",
        "whyThisMomentMatters": "The immediate, messy, and satisfying visual of pouring honey directly onto the face is a high-retention hook.",
        "mumukiReuseNote": "Use this as a 'texture hook' to show the richness of the MUMUKI ampoule, replacing honey with the product texture."
      },
      {
        "id": "7545915943940050231-041",
        "videoId": "7545915943940050231",
        "creator": "@jaimesskin",
        "title": "Manuka Honey Face Mask",
        "clipPath": "content/visual-hook-mining/clips/jaimesskin__manuka-honey-face-mask__7545915943940050231_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 3.0,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "Close-up of the creator's face completely covered in a thick, golden, sticky honey mask, holding a wooden spoon with honey.",
        "whyThisMomentMatters": "The immediate visual of a thick, sticky, golden mask on the face is highly arresting and signals a DIY skincare routine.",
        "mumukiReuseNote": "Use this as a high-impact hook for the MUMUKI ampoule, showing the product texture being applied similarly."
      },
      {
        "id": "7615701080982211853-071",
        "videoId": "7615701080982211853",
        "creator": "@tenishaward1",
        "title": "Brighter Clearer Skin",
        "clipPath": "content/visual-hook-mining/clips/tenishaward1__brighter-clearer-skin__7615701080982211853_v3_31flashlite/beat-02.mp4",
        "startSeconds": 2.5,
        "endSeconds": 5.0,
        "momentBucket": "product_application",
        "roleTag": "texture-demonstration",
        "clipPriority": 2,
        "visualEvidence": "Close-up of the brush spreading the smooth, thick yellow paste across the cheek and forehead.",
        "whyThisMomentMatters": "Demonstrates the satisfying, smooth texture of the DIY mask, which is highly relevant to the texture of an ampoule.",
        "mumukiReuseNote": "Show the MUMUKI ampoule being spread on the skin in a similar close-up to highlight its consistency."
      },
      {
        "id": "7579824086315011359-057",
        "videoId": "7579824086315011359",
        "creator": "@drewcanole",
        "title": "DIY Honey Face Mask",
        "clipPath": "content/visual-hook-mining/clips/drewcanole__diy-honey-face-mask__7579824086315011359_v3_31flashlite/beat-02.mp4",
        "startSeconds": 6.0,
        "endSeconds": 9.0,
        "momentBucket": "texture_shot",
        "roleTag": "sensory-appeal",
        "clipPriority": 2,
        "visualEvidence": "Close-up of a honey dipper dripping thick, golden raw honey.",
        "whyThisMomentMatters": "High-quality texture shots of natural ingredients are visually satisfying and build trust in the product's purity.",
        "mumukiReuseNote": "Create a similar high-definition macro shot of the MUMUKI ampoule texture to emphasize its richness."
      },
      {
        "id": "7446093862952815918-027",
        "videoId": "7446093862952815918",
        "creator": "@tenishaward1",
        "title": "Honey Comb Facial",
        "clipPath": "content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-02.mp4",
        "startSeconds": 3.0,
        "endSeconds": 6.0,
        "momentBucket": "ingredient_texture",
        "roleTag": "texture-focus",
        "clipPriority": 2,
        "visualEvidence": "Close-up of honey dripping and spreading across the creator's face, showing the sticky, thick consistency.",
        "whyThisMomentMatters": "Highlights the sensory appeal of honey as a skincare ingredient, which is a key selling point for the ampoule.",
        "mumukiReuseNote": "Showcase the ampoule's texture in a similar macro shot to emphasize its richness and quality."
      },
      {
        "id": "7593798567966297355-063",
        "videoId": "7593798567966297355",
        "creator": "@shamiebirungi19",
        "title": "Honey Skin Glow Hack",
        "clipPath": "content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-03.mp4",
        "startSeconds": 6.5,
        "endSeconds": 10.0,
        "momentBucket": "application_moment",
        "roleTag": "product-application",
        "clipPriority": 2,
        "visualEvidence": "The creator uses her fingers to spread the thick, sticky honey across her entire face.",
        "whyThisMomentMatters": "Shows the full coverage application process, which is essential for skincare tutorials.",
        "mumukiReuseNote": "Replicate this application motion with the MUMUKI ampoule to demonstrate ease of spread and coverage."
      },
      {
        "id": "7615701080982211853-072",
        "videoId": "7615701080982211853",
        "creator": "@tenishaward1",
        "title": "Brighter Clearer Skin",
        "clipPath": "content/visual-hook-mining/clips/tenishaward1__brighter-clearer-skin__7615701080982211853_v3_31flashlite/beat-03.mp4",
        "startSeconds": 5.0,
        "endSeconds": 7.5,
        "momentBucket": "product_application",
        "roleTag": "satisfying-application",
        "clipPriority": 3,
        "visualEvidence": "The creator is carefully applying the mask around the nose and mouth area with a brush.",
        "whyThisMomentMatters": "The precision application is visually satisfying and mimics the professional application of skincare products.",
        "mumukiReuseNote": "Use this to show the precision application of the MUMUKI ampoule around targeted areas."
      },
      {
        "id": "7593798567966297355-064",
        "videoId": "7593798567966297355",
        "creator": "@shamiebirungi19",
        "title": "Honey Skin Glow Hack",
        "clipPath": "content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-04.mp4",
        "startSeconds": 13.5,
        "endSeconds": 17.18,
        "momentBucket": "payoff_moment",
        "roleTag": "skin-glow",
        "clipPriority": 3,
        "visualEvidence": "The creator points to her cheek, highlighting the glossy, hydrated, and glowing finish of her skin.",
        "whyThisMomentMatters": "This is the 'payoff' that justifies the entire process; it proves the 'glow' result.",
        "mumukiReuseNote": "Essential for the 'After' shot of the MUMUKI ampoule to show the immediate skin radiance."
      },
      {
        "id": "7446093862952815918-029",
        "videoId": "7446093862952815918",
        "creator": "@tenishaward1",
        "title": "Honey Comb Facial",
        "clipPath": "content/visual-hook-mining/clips/tenishaward1__honey-comb-facial__7446093862952815918_v3_31flashlite/beat-04.mp4",
        "startSeconds": 12.0,
        "endSeconds": 15.0,
        "momentBucket": "skin_payoff",
        "roleTag": "result-focus",
        "clipPriority": 4,
        "visualEvidence": "The creator shows her face after the mask, highlighting a natural, dewy glow.",
        "whyThisMomentMatters": "Provides the 'payoff' that justifies the messy process, proving that the ingredient leads to visible skin improvement.",
        "mumukiReuseNote": "Use this as the 'after' shot to demonstrate the glow provided by the MUMUKI ampoule."
      },
      {
        "id": "7593798567966297355-062",
        "videoId": "7593798567966297355",
        "creator": "@shamiebirungi19",
        "title": "Honey Skin Glow Hack",
        "clipPath": "content/visual-hook-mining/clips/shamiebirungi19__honey-skin-glow-hack__7593798567966297355_v3_31flashlite/beat-02.mp4",
        "startSeconds": 3.5,
        "endSeconds": 6.0,
        "momentBucket": "action_moment",
        "roleTag": "visual-engagement",
        "clipPriority": 4,
        "visualEvidence": "The honey drips down the creator's nose and she licks it off, showing the raw nature of the ingredient.",
        "whyThisMomentMatters": "The interaction with the ingredient makes the DIY process feel authentic and relatable.",
        "mumukiReuseNote": "Not reusable as is, but the 'drip' visual can be adapted to show the ampoule's viscosity."
      },
      {
        "id": "7555933284388146454-047",
        "videoId": "7555933284388146454",
        "creator": "@kriziaraso",
        "title": "Honey Facial Glow",
        "clipPath": "content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-02.mp4",
        "startSeconds": 4.5,
        "endSeconds": 7.5,
        "momentBucket": "product_application",
        "roleTag": "visual-satisfaction",
        "clipPriority": 2,
        "visualEvidence": "The creator uses a small spatula to drizzle thick, golden honey directly onto her cheek.",
        "whyThisMomentMatters": "The viscous, golden texture of the honey is visually satisfying and highlights the raw ingredient focus.",
        "mumukiReuseNote": "Replicate this 'drip' shot with the MUMUKI ampoule to emphasize its rich, concentrated texture."
      },
      {
        "id": "7555933284388146454-048",
        "videoId": "7555933284388146454",
        "creator": "@kriziaraso",
        "title": "Honey Facial Glow",
        "clipPath": "content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-03.mp4",
        "startSeconds": 7.5,
        "endSeconds": 10.0,
        "momentBucket": "product_application",
        "roleTag": "visual-satisfaction",
        "clipPriority": 3,
        "visualEvidence": "The creator spreads the honey across her face with her fingers, creating a glossy, reflective layer.",
        "whyThisMomentMatters": "Shows the product coverage and the immediate 'glow' effect on the skin.",
        "mumukiReuseNote": "Show the application of the ampoule to demonstrate how it leaves a non-sticky, healthy glow."
      }
    ]
  },
  {
    "id": "frozen-banana-tool",
    "title": "Frozen Banana Tool",
    "label": "Banana as tool",
    "why": "Not a normal skincare action. The banana becomes a face-massage tool, which makes it useful for a strong skit opening.",
    "items": [
      {
        "id": "7621189679148272928-079",
        "videoId": "7621189679148272928",
        "creator": "@iamedsonbrandao",
        "title": "Frozen Banana Lift Hack",
        "clipPath": "content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 3.0,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "The creator holds two halves of a frozen, dark-spotted banana directly in front of the camera.",
        "whyThisMomentMatters": "The visual of a frozen banana used for skincare is highly unconventional and immediately grabs attention.",
        "mumukiReuseNote": "Use a similar 'What is this?' opening shot with the MUMUKI ampoule to create curiosity."
      },
      {
        "id": "7621189679148272928-080",
        "videoId": "7621189679148272928",
        "creator": "@iamedsonbrandao",
        "title": "Frozen Banana Lift Hack",
        "clipPath": "content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-02.mp4",
        "startSeconds": 3.5,
        "endSeconds": 6.5,
        "momentBucket": "application_moment",
        "roleTag": "visual-action",
        "clipPriority": 2,
        "visualEvidence": "The creator rubs the frozen banana halves along his jawline in a lifting motion.",
        "whyThisMomentMatters": "Demonstrates a clear, actionable 'hack' that viewers can mimic, proving the interest in DIY banana skincare.",
        "mumukiReuseNote": "Show the application of the MUMUKI ampoule using a similar upward lifting motion on the jawline."
      },
      {
        "id": "7621189679148272928-081",
        "videoId": "7621189679148272928",
        "creator": "@iamedsonbrandao",
        "title": "Frozen Banana Lift Hack",
        "clipPath": "content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-03.mp4",
        "startSeconds": 10.5,
        "endSeconds": 13.0,
        "momentBucket": "application_moment",
        "roleTag": "visual-action",
        "clipPriority": 3,
        "visualEvidence": "The creator rubs the flat surface of the frozen banana directly onto his cheek.",
        "whyThisMomentMatters": "Direct skin contact with the ingredient highlights the 'skincare' aspect of the hack.",
        "mumukiReuseNote": "Show the ampoule being applied directly to the cheek to emphasize hydration."
      },
      {
        "id": "7621189679148272928-082",
        "videoId": "7621189679148272928",
        "creator": "@iamedsonbrandao",
        "title": "Frozen Banana Lift Hack",
        "clipPath": "content/visual-hook-mining/clips/iamedsonbrandao__frozen-banana-lift-hack__7621189679148272928_v3_31flashlite/beat-04.mp4",
        "startSeconds": 17.0,
        "endSeconds": 20.0,
        "momentBucket": "application_moment",
        "roleTag": "visual-action",
        "clipPriority": 4,
        "visualEvidence": "The creator presses the frozen banana halves under his eyes.",
        "whyThisMomentMatters": "Targets a specific pain point (dark circles) with a simple visual action.",
        "mumukiReuseNote": "Show the ampoule being tapped gently under the eyes to address dark circles."
      }
    ]
  },
  {
    "id": "before-after-proof",
    "title": "Before / After Proof",
    "label": "Comparison proof",
    "why": "Gives the viewer a result direction immediately. It feels more like proof than a simple application shot.",
    "items": [
      {
        "id": "7555933284388146454-046",
        "videoId": "7555933284388146454",
        "creator": "@kriziaraso",
        "title": "Honey Facial Glow",
        "clipPath": "content/visual-hook-mining/clips/kriziaraso__honey-facial-glow__7555933284388146454_v3_31flashlite/beat-01.mp4",
        "startSeconds": 0.0,
        "endSeconds": 2.5,
        "momentBucket": "hook_moment",
        "roleTag": "stop-power",
        "clipPriority": 1,
        "visualEvidence": "The creator shows a split-screen comparison of her skin with acne (before) and her current clear, glowing skin.",
        "whyThisMomentMatters": "The dramatic before-and-after transformation immediately establishes credibility and high stakes for the viewer.",
        "mumukiReuseNote": "Use a similar split-screen format to show the immediate soothing effect of the MUMUKI ampoule on irritated skin."
      }
    ]
  }
];
